#we're making GitHub automatically perform those tests too.

name: CI   #continous integration workflow name

# Run the workflow whenever code is pushed
# or a pull request is created.
on:
  push:
  pull_request:

jobs:

  test:

    # Use a fresh Ubuntu machine
    runs-on: ubuntu-latest

    steps:

      # 1. Get our GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run our API tests
      - name: Run tests
        run: python -m pytest